spring:
  datasource:
    url: jdbc:h2:mem:hexagonal-db
    driverClassName: org.h2.Driver
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: create

me:
  arnedc:
    examples:
      architecture:
        hexagonal:
          database:
            server:
              tcp:
                port: 9090
